name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # Trigger on push to main branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-east2
  REPO_NAME: eightbitstore-repo
  IMAGE_NAME: eightbitstore-api
  SERVICE_NAME: eightbitstore-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker Image
        working-directory: ./8bitstore-be
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          env_vars: |
            ASPNETCORE_ENVIRONMENT=Production
          secrets: |
            ConnectionStrings__WebApiDatabase=NEON_DB_CONNECTION_STRING:latest
            Redis__ConnectionString=REDIS_CONNECTION_STRING:latest
            Vnpay__TmnCode=VNPAY_TMNCODE:latest
            Vnpay__HashSecret=VNPAY_HASHSECRET:latest
            Vnpay__BaseUrl=VNPAY_BASEURL:latest
            Vnpay__PaymentBackReturnUrl=VNPAY_RETURNURL:latest
            EmailSetting__SmtpHost=SMTP_HOST:latest
            EmailSetting__SmtpPort=SMTP_PORT:latest
            EmailSetting__SmtpUser=SMTP_USER:latest
            EmailSetting__SmtpPass=SMTP_PASS:latest
            EmailSetting__FromEmail=SMTP_FROM_EMAIL:latest
          flags: '--allow-unauthenticated --port=8080'
